# Generated by Django 4.1.6 on 2023-02-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach_Xu_Wenwu', '0002_users_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
