# Generated by Django 4.1.6 on 2023-02-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach_Xu_Wenwu', '0003_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
            ],
        ),
    ]
