# Generated by Django 4.1.6 on 2023-02-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_Xu_Wenwu', '0005_pickdate_email_pickdate_name_pickdate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickdate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
