# Generated by Django 4.1.6 on 2023-02-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_Xu_Wenwu', '0006_pickdate_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickdate',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pickdate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
